version: "3.9"


services:

  db:
    image: postgres
    restart: always
    ports: 
      - 5432:5432
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}

  app:
    container_name: app
    build: .
    environment: 
      - DB_HOST=${DB_HOST}
      - DB_NAME=${DB_NAME}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_PORT=${DB_PORT}
      - DB_USER=${DB_USER}
      - APP_NAME=${APP_NAME}
    env_file:
      - ./.env
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./passwordShare:/passwordShare
    ports:
      - 8000:8000
    restart: always
    depends_on:
      - db
volumes:
  postgres_data:
  
  