version: "3.9"


services:

  db:
    image: postgres
    restart: always
    ports: 
      - 5432:5432
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}

  app:
    container_name: app
    build: .
    environment: 
      - DB_HOST=${DB_HOST}
      - DB_NAME=${DB_NAME}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_PORT=${DB_PORT}
      - DB_USER=${DB_USER}
      - APP_NAME=${APP_NAME}
    env_file:
      - ./.env
    command: ./entrypoint.sh #gunicorn core.wsgi:application --bind :8000 #python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./passwordShare:/passwordShare
      - static_volumes:/staticfiles
    expose:
      - 8000
    restart: on-failure
    depends_on:
      - db
  nginx:
    build: ./nginx
    ports:
      - 1337:80
    volumes:
      - static_volumes:/staticfiles
    depends_on:
      - app
volumes:
  postgres_data:
  static_volumes:
  
  