# Generated by Django 4.0.5 on 2022-07-18 01:41

from django.db import migrations, models
import django_cryptography.fields
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SharedSecret',
            fields=[
                ('name', models.CharField(max_length=100)),
                ('text', django_cryptography.fields.encrypt(models.TextField(max_length=250))),
                ('ttl', models.SmallIntegerField(default=1)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('accessed', models.PositiveSmallIntegerField(default=0)),
            ],
        ),
    ]
